export interface IObject{
    [key: string]: string
}

export enum SVG_SELECTION{ADD, EDIT, DELETE, DRAG, MOREV, MOREH, INFO, HELP, LOGIN, LOGOUT, IMPORT, EXPORT, SAVE, LOAD,
    SETTINGS, PROPERTIES, SEARCH, LIKE, LIKE_EMPTY, COPY, EMAIL, PASSWORD, SEND, UNDO, REDO};

export enum PlayerStyle {NONE, CIRCLE, JERSEY, FACE};